---
default:
  labels:
    - color: 8fc951
      description: Indicates an issue or PR is ready to be actively worked on.
      name: triage/accepted
      target: both
      prowPlugin: label
      addedBy: org members
    - color: d455d0
      description: Indicates an issue is a duplicate of other open issue.
      name: triage/duplicate
      target: both
      addedBy: anyone
    - color: d455d0
      description: Indicates an issue needs more information in order to work on it.
      name: triage/needs-information
      target: both
      addedBy: anyone
    - color: d455d0
      description: Indicates an issue can not be reproduced as described.
      name: triage/not-reproducible
      target: both
      addedBy: anyone
    - color: d455d0
      description: Indicates an issue that can not or will not be resolved.
      name: triage/unresolved
      target: both
      addedBy: anyone
    - color: 8452c9
      name: triage/build-watcher
      target: issues
      description: Discovered by a kubevirt build-watcher. Pay attention to these issues to keep CI healthy.
      prowPlugin: label
      addedBy: anyone
      previously:
        - name: triage/build-officer
          color: 8452c9
    - color: c2e0c6
      name: release-note
      target: prs
      description: Denotes a PR that will be considered when it comes time to generate release notes.
      prowPlugin: release-note
      addedBy: prow
    - color: c2e0c6
      description: Denotes a PR that introduces potentially breaking changes that require user action. # These actions will be specifically called out when it comes time to generate release notes.
      name: release-note-action-required
      target: prs
      prowPlugin: releasenote
      addedBy: prow
    - color: c2e0c6
      description: Denotes a PR that doesn't merit a release note.  # will be ignored when it comes time to generate release notes.
      name: release-note-none
      target: prs
      prowPlugin: release-note
      addedBy: prow
    - color: e11d21
      description: Indicates that a PR should not merge because someone has issued a /hold command.
      name: do-not-merge/hold
      target: prs
      prowPlugin: hold
      addedBy: anyone
    - color: e11d21
      description: Indicates that a PR should not merge because it is a work in progress.
      name: do-not-merge/work-in-progress
      target: prs
      prowPlugin: wip
      addedBy: prow
    - color: BDBDBD
      description: Indicates a PR cannot be merged because it has merge conflicts with HEAD.
      name: needs-rebase
      target: prs
      prowPlugin: needs-rebase
      addedBy: prow
    - color: e11d21
      description: Indicates that a PR should not merge because it's missing one of the release note labels.
      name: do-not-merge/release-note-label-needed
      previously:
        - name: needs/release-note
          color: d4c5f9
      target: prs
      addedBy: prow
      prowPlugin: release-note
    - name: kind/blocker
      color: b60205
      target: both
      addedBy: anyone
      prowPlugin: label
    - name: kind/bug
      color: ee0701
      target: both
      addedBy: anyone
      prowPlugin: label
    - name: kind/enhancement
      color: bfd4f2
      target: both
      addedBy: anyone
      prowPlugin: label
    - name: kind/proposal
      color: bfd4f2
      target: both
      addedBy: anyone
      prowPlugin: label
    - name: kind/question
      color: cc317c
      target: both
      addedBy: anyone
      prowPlugin: label
    - name: kind/tracker
      color: bc19c1
      target: both
      addedBy: anyone
      prowPlugin: label
    - color: e11d21
      description: Categorizes issue or PR as related to adding, removing, or otherwise changing an API
      name: kind/api-change
      target: both
      prowPlugin: label
      addedBy: anyone
    - name: size/L
      color: ee9900
      target: both
      previously:
        - name: size-L
          color: f9d0c4
      addedBy: prow
      prowPlugin: size
    - name: size/M
      color: eebb00
      target: both
      previously:
        - name: size-M
          color: f9d0c4
      addedBy: prow
      prowPlugin: size
    - name: size/S
      color: 77bb00
      target: both
      previously:
        - name: size-S
          color: f9d0c4
      addedBy: prow
      prowPlugin: size
    - name: size/XL
      color: ee5500
      target: both
      previously:
        - name: size-XL
          color: f9d0c4
      addedBy: prow
      prowPlugin: size
    - color: "009900"
      name: size/XS
      target: both
      addedBy: prow
      prowPlugin: size
    - color: ee0000
      name: size/XXL
      target: both
      addedBy: prow
      prowPlugin: size
    - color: d3e2f0
      description: Indicates that an issue or PR should not be auto-closed due to staleness.
      name: lifecycle/frozen
      target: both
      prowPlugin: lifecycle
      addedBy: prow
    - color: 8fc951
      description: Indicates that an issue or PR is actively being worked on by a contributor.
      name: lifecycle/active
      target: both
      prowPlugin: lifecycle
      addedBy: prow
    - color: "604460"
      description: Denotes an issue or PR that has aged beyond stale and will be auto-closed.
      name: lifecycle/rotten
      target: both
      prowPlugin: lifecycle
      addedBy: prow
    - color: "795548"
      description: Denotes an issue or PR has remained open with no activity and has become stale.
      name: lifecycle/stale
      target: both
      prowPlugin: lifecycle
      addedBy: prow
    - name: sig/network
      color: c5def5
      target: both
      prowPlugin: label
      addedBy: anyone
      previously:
        - name: topic/network
          color: c5def5
    - name: sig/security
      color: c5def5
      target: both
      prowPlugin: label
      addedBy: anyone
      previously:
        - name: topic/security
          color: c5def5
    - name: sig/storage
      color: c5def5
      target: both
      prowPlugin: label
      addedBy: anyone
      previously:
        - name: topic/storage
          color: c5def5
    - name: sig/virtualization
      color: c5def5
      target: both
      prowPlugin: label
      addedBy: anyone
      previously:
        - name: topic/virtualization
          color: c5def5
    - name: sig/code-quality
      color: ce23cf
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: e11d21
      description: Indicates the PR's author has not DCO signed all their commits.
      name: "dco-signoff: no"
      target: prs
      prowPlugin: dco
      addedBy: prow
    - color: bfe5bf
      description: Indicates the PR's author has DCO signed all their commits.
      name: "dco-signoff: yes"
      target: prs
      prowPlugin: dco
      addedBy: prow
    - color: 15dd18
      description: Indicates that a PR is ready to be merged.
      name: lgtm
      target: prs
      prowPlugin: lgtm
      addedBy: reviewers or members
    - color: 0ffa16
      description: Indicates a PR has been approved by an approver from all required OWNERS files.
      name: approved
      target: prs
      prowPlugin: approve
      addedBy: approvers
    - color: b60205
      description: Indicates a PR that requires an org member to verify it is safe to test. # This is to prevent spam/abuse of our CI system, and can be circumvented by becoming an org member. Org members can remove this label with the `/ok-to-test` command.
      name: needs-ok-to-test
      target: prs
      prowPlugin: trigger
      addedBy: prow
    - color: 15dd18
      description: Indicates a non-member PR verified by an org member that is safe to test. # This is the opposite of needs-ok-to-test and should be mutually exclusive.
      name: ok-to-test
      target: prs
      prowPlugin: trigger
      addedBy: prow
repos:
  kubevirt/kubevirt:
    labels:
      - name: needs/documentation
        color: d4c5f9
        target: both
      - name: priority/backlog
        color: fbca04
        target: both
      - name: priority/critical-urgent
        color: d93f0b
        target: both
      - name: research-needed
        color: fef2c0
        target: both
      - name: wontfix
        color: ffffff
        target: both
      - name: duplicate
        color: cccccc
        target: both
      - name: for/developers
        color: fef2c0
        target: both
      - name: for/users
        color: fef2c0
        target: both
      - name: good-first-issue
        color: 128A0C
        target: issues
        previously:
          - name: good first issue
            color: 128A0C
      - name: help-wanted
        color: 128A0C
        target: issues
        previously:
        - name: help wanted
          color: 128A0C
      - name: distro/kubernetes
        color: fcb3ad
        target: both
        previously:
        - name: distro/kuberenetes
          color: fcb3ad
      - name: distro/openshift
        color: fcb3ad
        target: both
      - name: area/operator
        color: bfd4f2
        target: both
      - name: area/api-server
        color: bfd4f2
        target: both
      - name: area/controller
        color: bfd4f2
        target: both
      - name: area/handler
        color: bfd4f2
        target: both
      - name: area/launcher
        color: bfd4f2
        target: both
      - name: area/virtctl
        color: bfd4f2
        target: both
      - name: area/monitoring
        color: bfd4f2
        target: both
      - name: area/instancetype
        color: bfd4f2
        target: both
      - name: topic/api
        color: c5def5
        target: both
      - name: topic/build
        color: c5def5
        target: both
      - name: topic/ci
        color: c5def5
        target: both
      - name: topic/client
        color: c5def5
        target: both
      - name: topic/community
        color: c5def5
        target: both
      - name: topic/documentation
        color: c5def5
        target: both
      - name: topic/infrastructure
        color: c5def5
        target: both
      - name: topic/integration
        color: c5def5
        target: both
      - name: topic/packaging
        color: c5def5
        target: both
      - name: topic/scheduling
        color: c5def5
        target: both
      - name: topic/testing
        color: c5def5
        target: both
      - color: e11d21
        description: Categorizes PRs as related to changing build files of virt-* components
        name: kind/build-change
        target: prs
        prowPlugin: label
        addedBy: anyone
      - color: bf0004
        description: Indicates that a PR or issue is blocking a release from a specific branch.
        name: release-blocker
        target: both
        prowPlugin: release-blocker
        addedBy: prow
  kubevirt/kubevirt.github.io:
    labels:
      - color: 80e591
        description: Label for blog entries
        name: kind/blog
        target: prs
        addedBy: anyone
        prowPlugin: label
      - color: 064d70
        description: Label for web site management/maintenance/...
        name: kind/website
        target: both
        addedBy: anyone
        prowPlugin: label
  kubevirt/kubevirt-tutorial:
    labels:
      - color: 80e591
        description: Label for new Labs included
        name: kind/new-lab
        target: prs
        addedBy: anyone
        prowPlugin: label
      - color: 064d70
        description: Label for Lab deployment inclusion
        name: kind/lab-deployment
        target: prs
        addedBy: anyone
        prowPlugin: label
      - name: kind/lab-updates
        description: Label for Labs updates
        color: bfd4f2
        target: pr
        addedBy: anyone
        prowPlugin: label
  kubevirt/hyperconverged-cluster-operator:
    labels:
      - color: e11d21
        description: Needed to be compatible with openshift CI
        name: tide/merge-blocker
        target: prs
        addedBy: openshift-ci
        prowPlugin: label
  kubevirt/project-infra:
    labels:
      - addedBy: anyone
        color: 81F2B9
        description: Issues and PRs concerning FlakeFinder, a tool to find flaky tests
        name: area/flakefinder
        prowPlugin: label
        target: both
      - addedBy: anyone
        color: AB72F2
        description: Issues and PRs concerning KubeVirt Prow, i.e. configuration, setup etc.
        name: area/prow
        prowPlugin: label
        target: both
      - addedBy: anyone
        color: F2E75C
        description: Issues and PRs concerning automation, i.e. KubeVirt job updates, KubeVirtCI bumps etc.
        name: area/automation
        prowPlugin: label
        target: both
      - addedBy: anyone
        color: F2E75C
        description: Issues and PRs concerning monitoring of Prow components
        name: area/monitoring
        prowPlugin: label
        target: both
  nmstate/kubernetes-nmstate:
    labels:
      - name: kind/documentation
        color: 167e8c
        target: both
        prowPlugin: label
        addedBy: anyone
      - name: kind/feature
        color: 1a7f08
        target: both
        prowPlugin: label
        addedBy: anyone
      - name: kind/infrastructure
        color: c90c67
        target: both
        prowPlugin: label
        addedBy: anyone
      - name: kind/refactor
        color: 842700
        target: both
        prowPlugin: label
        addedBy: anyone
      - name: kind/test
        color: 114d6d
        target: both
        prowPlugin: label
        addedBy: anyone
      - name: priority/highest
        color: fbca04
        target: both
      - name: priority/high
        color: adadeb
        target: both
      - name: priority/medium
        color: c2c2f0
        target: both
      - name: priority/low
        color: d6d6f5
        target: both
      - name: priority/lowest
        color: ebebfa
        target: both
      - name: duplicate
        color: cccccc
        target: both
      - name: invalid
        color: ffffff
        target: both
      - name: good first issue
        color: 128A0C
        target: issues
      - name: help wanted
        color: 128A0C
        target: issues
