- name: "{{ name_header }} : Render manifest source file"
  include_tasks: _manifest_source.yaml
  vars:
    kubeconfig: '{{ _kubeconfig_path }}'

- name: "{{ name_header }} : invoke kubectl"
  no_log: not show_sensitive
  k8s:
    kubeconfig: '{{ _kubeconfig_path }}'
    context: '{{ _context }}'
    state: absent
    namespace: "{{ namespace }}"
    validate:
      fail_on_error: "{{ fatal_validation|bool }}"
      strict: "{{ strict_validation|bool }}"
    src: "{{ resource_tempfile.path }}"

- name: "{{ name_header }} : remove source file"
  file:
    path: "{{ resource_tempfile.path }}"
    state: absent
