resources:
  - manifests/local/branch-protector.yaml
  - manifests/local/cherrypicker_deployment.yaml
  - manifests/local/cherrypicker_service.yaml
  - manifests/test_infra/current/crier_deployment.yaml
  - manifests/test_infra/current/crier_rbac.yaml
  - manifests/test_infra/current/crier_service.yaml
  - manifests/test_infra/current/deck_deployment.yaml
  - manifests/test_infra/current/deck_rbac.yaml
  - manifests/test_infra/current/deck_service.yaml
  - manifests/local/exporter-deployment.yaml
  - manifests/local/exporter-rbac.yaml
  - manifests/local/gcsweb-deployment.yaml
  - manifests/local/gcsweb-service.yaml
  - manifests/test_infra/current/ghproxy.yaml
  - manifests/local/greenhouse-deployment.yaml
  - manifests/local/greenhouse-pvc.yaml
  - manifests/local/greenhouse-service.yaml
  - manifests/test_infra/current/hook_deployment.yaml
  - manifests/test_infra/current/hook_rbac.yaml
  - manifests/test_infra/current/hook_service.yaml
  - manifests/test_infra/current/horologium_deployment.yaml
  - manifests/test_infra/current/horologium_rbac.yaml
  - manifests/test_infra/current/horologium_service.yaml
  # Specific to GCE
  # - manifests/test_infra/ing_ingress.yaml
  - manifests/local/nginx-ingress.yaml
  - manifests/local/label-sync-kubevirt.yaml
  - manifests/local/label-sync-nmstate.yaml
  - manifests/local/docker-mirror_deployment.yaml
  - manifests/local/docker-mirror_service.yaml
  - manifests/test_infra/current/needs-rebase_deployment.yaml
  - manifests/test_infra/current/needs-rebase_service.yaml
  - manifests/test_infra/current/plank_deployment.yaml
  - manifests/test_infra/current/plank_rbac.yaml
  - manifests/test_infra/current/plank_service.yaml
  - manifests/test_infra/current/prowjob_customresourcedefinition.yaml
  - manifests/local/prow-rehearse-rbac.yaml
  - manifests/local/prow-rehearse-deployment.yaml
  - manifests/local/prow-rehearse-service.yaml
  - manifests/test_infra/current/pushgateway_deployment.yaml
  - manifests/local/release-blocker_deployment.yaml
  - manifests/local/release-blocker_service.yaml
  - manifests/test_infra/current/sinker_deployment.yaml
  - manifests/test_infra/current/sinker_rbac.yaml
  - manifests/test_infra/current/sinker_service.yaml
  - manifests/test_infra/current/statusreconciler_deployment.yaml
  - manifests/test_infra/current/statusreconciler_rbac.yaml
  - manifests/test_infra/current/tide_deployment.yaml
  - manifests/test_infra/current/tide_rbac.yaml
  - manifests/local/tide_rbac_prowjob.yaml
  - manifests/test_infra/current/tide_service.yaml