# Requires kustomize v3
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/bootstrap.yaml

patches:
  - target:
      version: v1
      kind: Secret
      namespace: ""
      name: .*
    path: patches/JsonRFC6902/prow-jobs-namespace.yaml
  - target:
      version: v1
      kind: ConfigMap
      namespace: ""
      name: .*
    path: patches/JsonRFC6902/prow-jobs-namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: docker-daemon-mirror-config
    files:
      - config.yaml=configs/mirror/mirror.yaml
  - name: mirror-proxy-config
    files:
      - configs/mirror-proxy/ca.crt

secretGenerator:
  - name: gcs
    files:
      - secrets/gcs-service-account.json
    type: Opaque
  - name: docker-mirror-proxy
    files:
      - ca.key=secrets/docker-proxy-ca.key
    type: Opaque

  - name: kubevirtci-docker-credential
    # username=dockerUser
    # password=dockerPass
    envs:
    - secrets/kubevirtci-docker-credential
    type: Opaque

  - name: kubevirtci-quay-credential
    # username=quayUser
    # password=quayPass
    envs:
    - secrets/kubevirtci-quay-credential
    type: Opaque
  - name: kubevirtci-installer-pull-token
    files:
      # installerPullToken
      - token=secrets/kubevirtci-installer-pull-token
    type: Opaque
  - name: kubevirtci-coveralls-token
    files:
      # coverallsToken
      - token=secrets/kubevirtci-coveralls-token
    type: Opaque
