dashboards:
- name: kubevirt-containerized-data-importer
- name: kubevirt-presubmits
- name: kubevirt-periodics
- name: kubevirt-libguestfs-appliance-periodics

dashboard_groups:
- name: kubevirt
  dashboard_names:
  - kubevirt-containerized-data-importer
  - kubevirt-presubmits
  - kubevirt-periodics
  - kubevirt-libguestfs-appliance-periodics
