---
gitHubToken: "/etc/github/oauth"
includedConfigPaths:
  - "/config/github/ci/prow-deploy/files/jobs"
excludedConfigPaths: []
targetVersion: latest
upstreamURLBase: "https://raw.githubusercontent.com/kubernetes/test-infra/master"
prefixes:
  - name: "Jobs"
    prefix: "us-docker.pkg.dev/k8s-infra-prow/images"
    summarise: true
    consistentImages: true
