---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: token-counter
  labels:
    app: token-counter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: token-counter
    spec:
      containers:
      - name: token-counter
        args:
        - --stderrthreshold=0
        - --prom-only
        - --token=/github-tokens/oauth
        image: kubevirtci/token-counter:v20190222-092216
        volumeMounts:
        - mountPath: /github-tokens
          readOnly: true
          name: github-tokens-secret
      volumes:
      - name: github-tokens-secret
        secret:
          secretName: oauth-token
---
apiVersion: v1
kind: Service
metadata:
  name: token-counter-metrics
spec:
  selector:
    app: token-counter
  ports:
  - name: default
    protocol: TCP
    port: 80
    targetPort: 9090
