postsubmits:
  kubevirt/application-aware-quota:
  - name: push-release-aaq-images
    branches:
    # regex for semver from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
    - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
    cluster: prow-workloads
    always_run: true
    optional: false
    skip_report: true
    annotations:
      testgrid-create-test-group: "false"
    decorate: true
    decoration_config:
      timeout: 1h
      grace_period: 5m
    labels:
      preset-podman-in-container-enabled: "true"
      preset-kubevirtci-quay-credential: "true"
    spec:
      containers:
      - image: quay.io/kubevirtci/bootstrap:v20251218-e7a7fc9
        env:
        - name: DOCKER_PREFIX
          value: quay.io/kubevirt
        command:
        - "/usr/local/bin/runner.sh"
        - "/bin/sh"
        - "-c"
        - |
          cat "$QUAY_PASSWORD" | docker login --username $(cat "$QUAY_USER") --password-stdin=true quay.io &&
          # Only push images on tags
          [ -z "$(git tag --points-at HEAD | head -1)" ] ||
          DOCKER_TAG="$(git tag --points-at HEAD | head -1)" make push-multi-arch
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "8Gi"
  - name: push-latest-aaq-images
    branches:
    - main
    cluster: prow-workloads
    always_run: true
    optional: false
    skip_report: true
    annotations:
      testgrid-create-test-group: "false"
    decorate: true
    decoration_config:
      timeout: 1h
      grace_period: 5m
    labels:
      preset-podman-in-container-enabled: "true"
      preset-kubevirtci-quay-credential: "true"
    spec:
      containers:
      - image: quay.io/kubevirtci/bootstrap:v20251218-e7a7fc9
        env:
        - name: DOCKER_PREFIX
          value: quay.io/kubevirt
        command:
        - "/usr/local/bin/runner.sh"
        - "/bin/sh"
        - "-c"
        - |
          cat "$QUAY_PASSWORD" | docker login --username $(cat "$QUAY_USER") --password-stdin=true quay.io &&
          DOCKER_TAG="latest" make push-multi-arch
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "8Gi"
  - name: push-aaq-tag
    branches:
    # regex for semver from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
    - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
    cluster: kubevirt-prow-control-plane
    always_run: true
    optional: false
    skip_report: true
    annotations:
      testgrid-create-test-group: "false"
    decorate: true
    decoration_config:
      timeout: 3h
      grace_period: 5m
    labels:
      preset-podman-in-container-enabled: "true"
      preset-github-credentials: "true"
    spec:
      containers:
      - image: quay.io/kubevirtci/bootstrap:v20251218-e7a7fc9
        env:
        - name: DOCKER_PREFIX
          value: quay.io/kubevirt
        - name: GH_CLI_VERSION
          value: "1.5.0"
        - name: GITHUB_TOKEN_PATH
          value: /etc/github/oauth
        - name: GITHUB_REPOSITORY
          value: kubevirt/application-aware-quota
        - name: GIT_USER_NAME
          value: kubevirt-bot
        command: [ "/usr/local/bin/runner.sh", "/bin/sh", "-c" ]
        args:
        - ./automation/release.sh
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "8Gi"
  - name: push-aaq-main
    branches:
    - main
    cluster: kubevirt-prow-control-plane
    always_run: true
    optional: false
    skip_report: true
    annotations:
      testgrid-create-test-group: "false"
    decorate: true
    decoration_config:
      timeout: 3h
      grace_period: 5m
    labels:
      preset-podman-in-container-enabled: "true"
      preset-github-credentials: "true"
    spec:
      containers:
      - image: quay.io/kubevirtci/bootstrap:v20251218-e7a7fc9
        env:
        - name: DOCKER_PREFIX
          value: quay.io/kubevirt
        - name: GH_CLI_VERSION
          value: "1.5.0"
        - name: GITHUB_TOKEN_PATH
          value: /etc/github/oauth
        - name: GITHUB_REPOSITORY
          value: kubevirt/application-aware-quota
        - name: GIT_USER_NAME
          value: kubevirt-bot
        command: [ "/usr/local/bin/runner.sh", "/bin/sh", "-c" ]
        args:
        - ./automation/postsubmit-main.sh
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "8Gi"
  - name: push-aaq-builder
    branches:
    - main
    cluster: prow-workloads
    always_run: false
    run_if_changed: "hack/build/builder/.*"
    optional: false
    skip_report: true
    annotations:
      testgrid-create-test-group: "false"
    decorate: true
    decoration_config:
      timeout: 3h
      grace_period: 5m
    max_concurrency: 1
    labels:
      preset-podman-in-container-enabled: "true"
      preset-docker-mirror-proxy: "true"
      preset-gcs-credentials: "true"
      preset-github-credentials: "true"
      preset-kubevirtci-quay-credential: "true"
    spec:
      nodeSelector:
        type: bare-metal-external
      containers:
      - image: quay.io/kubevirtci/bootstrap:v20251218-e7a7fc9
        env:
        - name: DOCKER_PREFIX
          value: quay.io/kubevirt
        command:
          - "/usr/local/bin/runner.sh"
          - "/bin/sh"
          - "-c"
          - |
            set -e
            cat "$QUAY_PASSWORD" | podman login quay.io --username $(cat "$QUAY_USER") --password-stdin=true
            make builder-push
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "8Gi"
