---
- name: Add admins to the pow job namespace
  command: "oc --kubeconfig {{ targetKubeconfig }} --context {{ targetContext }} -n {{ targetNamespace }} apply -f -"
  args:
    stdin: "{{ lookup('template', '{{ role_path }}/templates/admin-rbac.yaml')}}"
- name: Deploy job limit range
  command: "oc --kubeconfig {{ targetKubeconfig }} --context {{ targetContext }} -n {{ targetNamespace }} apply -f -"
  args:
    stdin: "{{ lookup('file', '{{ role_path }}/templates/memory-job-defaults.yaml') }}"
- name: Update the docker daemon mirror config
  k8s:
    kubeconfig: '{{ targetKubeconfig }}'
    context: '{{ targetContext }}'
    state: present
    namespace: "{{ targetNamespace }}"
    definition: "{{ lookup('template', '{{ role_path }}/templates/docker-daemon-mirror-config.yaml') | from_yaml }}"
  vars:
    dockerDaemonConfig: "{{ lookup('file', '{{ role_path }}/files/docker-daemon-mirror.conf') }}"
    dockerDaemonProxyConfig: "{{ lookup('file', '{{ role_path }}/files/docker-daemon-mirror-proxy.conf') }}"
- name: Create docker mirror proxy secret
  k8s:
    kubeconfig: '{{ automationKubeconfig }}'
    context: '{{ masterClusterContext }}'
    state: present
    namespace: "{{ prowNamespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: docker-mirror-proxy
      type: Opaque
      data:
        ca.key: "{{ dockerMirrorProxyCA.key | b64encode }}"
- name: Create docker mirror proxy config for proxy container
  k8s:
    kubeconfig: '{{ automationKubeconfig }}'
    context: '{{ masterClusterContext }}'
    state: present
    namespace: "{{ prowNamespace }}"
    definition: "{{ lookup('template', '{{ role_path }}/templates/mirror-proxy-config.yaml') | from_yaml }}"
- name: Create docker mirror proxy config for daemons
  k8s:
    kubeconfig: '{{ automationKubeconfig }}'
    context: '{{ masterClusterContext }}'
    state: present
    namespace: "{{ prowJobsNamespace }}"
    definition: "{{ lookup('template', '{{ role_path }}/templates/mirror-proxy-config.yaml') | from_yaml }}"
- name: Create docker mirror proxy service
  k8s:
    kubeconfig: '{{ automationKubeconfig }}'
    context: '{{ masterClusterContext }}'
    state: present
    namespace: "{{ prowNamespace }}"
    definition: "{{ lookup('template', '{{ role_path }}/templates/mirror-proxy-service.yaml') | from_yaml }}"
