# Requires kustomize v3
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../components/docker-mirror-proxy/base
  - ../../components/greenhouse/base
  - resources/docker-mirror-proxy_pvc.yaml
  - resources/hook-rbac.yaml
  - resources/horologium-rbac.yaml
  - resources/sinker-rbac.yaml
  - resources/prow-exporter-deployment.yaml
  - resources/prow-exporter-rbac.yaml
  - resources/prow-exporter-service.yaml
  - resources/ci-usage-exporter-deployment.yaml
  - resources/ci-usage-exporter-service.yaml
  # templated resources
  - resources/admin-rbac.yaml

components:
  - ../../components/docker-mirror-proxy/pv
  - ../../components/greenhouse/pv

patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: rehearse
    path: patches/JsonRFC6902/prow-rehearse-deployment.yaml
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: gcsweb
    path: patches/JsonRFC6902/gcsweb-deployment.yaml
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: deck
    path: patches/JsonRFC6902/deck_deployment.yaml
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: hook
    path: patches/JsonRFC6902/hook_deployment.yaml
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: tide
    path: patches/JsonRFC6902/tide_deployment.yaml
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: crier
    path: patches/JsonRFC6902/crier_deployment.yaml
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: prow-controller-manager
    path: patches/JsonRFC6902/prow_controller_manager_deployment.yaml
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: sinker
    path: patches/JsonRFC6902/sinker_deployment.yaml
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: ghproxy
    path: patches/JsonRFC6902/ghproxy_deployment.yaml
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: pushgateway
    path: patches/JsonRFC6902/pushgateway_deployment.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      namespace: test-pods
      name: deck
    path: patches/StrategicMerge/deck_role.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: docker-mirror
    path: patches/StrategicMerge/docker-mirror_deployment.yaml
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: ghproxy
    path: patches/StrategicMerge/ghproxy.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      namespace: test-pods
      name: crier
    path: patches/StrategicMerge/crier_role.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      namespace: test-pods
      name: prow-controller-manager
    path: patches/StrategicMerge/prow_controller_manager_role.yaml


  # namespaces
  - target:
      group: apps
      version: v1
      kind: Deployment
      namespace: default
      name: .*
    path: patches/JsonRFC6902/prow-namespace.yaml
  - target:
      version: v1
      kind: PersistentVolumeClaim
      namespace: default
      name: .*
    path: patches/JsonRFC6902/prow-namespace.yaml
  - target:
      version: v1
      kind: Service
      namespace: default
      name: .*
    path: patches/JsonRFC6902/prow-namespace.yaml
  - target:
      version: v1
      kind: ConfigMap
      namespace: default
      name: .*
    path: patches/JsonRFC6902/prow-namespace.yaml
  - target:
      version: v1
      kind: ServiceAccount
      namespace: default
      name: .*
    path: patches/JsonRFC6902/prow-namespace.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      namespace: default
      name: .*
    path: patches/JsonRFC6902/prow-namespace.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      namespace: default
      name: .*
    path: patches/JsonRFC6902/prow-namespace.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      namespace: test-pods
      name: .*
    path: patches/JsonRFC6902/prow-jobs-namespace.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      namespace: test-pods
      name: .*
    path: patches/JsonRFC6902/prow-jobs-namespace.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      namespace: test-pods
      name: .*
    path: patches/JsonRFC6902/prow-jobs-namespace.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: prow-rehearse
    path: patches/JsonRFC6902/rolebinding-subject-prow-namespace.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      namespace: test-pods
      name: .*
    path: patches/JsonRFC6902/rolebinding-subject-prow-namespace.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      namespace: test-pods
      name: .*
    path: patches/JsonRFC6902/rolebinding-subject-prow-namespace.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      namespace: default
      name: .*
    path: patches/JsonRFC6902/prow-namespace.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      namespace: test-pods
      name: .*
    path: patches/JsonRFC6902/prow-jobs-namespace.yaml
  - target:
      group: rbnac.authorization.k8s.io
      version: v1
      kind: Role
      namespace: test-pods
      name: .*
    path: patches/JsonRFC6902/prow-jobs-namespace.yaml
  - target:
      group: rbac.authorization.k8s.io
      kind: Role
      namespace: test-pods
      name: deck
    path: patches/JsonRFC6902/prow-jobs-rolebinding-rules.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      namespace: default
      name: .*
    path: patches/JsonRFC6902/prow-namespace.yaml
  - target:
      version: v1
      kind: Secret
      namespace: default
      name: .*
    path: patches/JsonRFC6902/prow-namespace.yaml
  - target:
      version: v1
      kind: ConfigMap
      namespace: ""
      name: .*
    path: patches/JsonRFC6902/prow-namespace.yaml
  - target:
      group: batch
      version: v1
      kind: CronJob
      namespace: ""
      name: .*
    path: patches/JsonRFC6902/prow-namespace.yaml


generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: config
    files:
      - configs/config/config.yaml
  - name: label-config
    files:
      - configs/labels/labels.yaml
  - name: plugins
    files:
      - configs/plugins/plugins.yaml
  - name: cat-api-key
    files:
      - configs/cat-api/api-key

secretGenerator:
  - name: oauth-token
    files:
      - oauth=secrets/oauth-token
    type: Opaque
  - name: oauth-token
    namespace: kubevirt-prow-jobs
    files:
      - oauth=secrets/oauth-token
    type: Opaque
  - name: gcs
    files:
      - secrets/service-account.json
    type: Opaque
  - name: gcs
    namespace: kubevirt-prow-jobs
    files:
      - secrets/service-account.json
    type: Opaque
  - name: slack-token
    files:
      - token=secrets/slack-token
    type: Opaque
  - name: cookie
    files:
      - secret=secrets/cookie
    type: Opaque
  - name: github-oauth-config
    files:
      - secret=secrets/github-oauth-config
    type: Opaque
  - name: kubeconfig
    files:
      - config=secrets/kubeconfig
    type: Opaque
  - name: kubeconfig-build-test-infra-trusted
    files:
      - kubeconfig=secrets/kubeconfig-build-test-infra-trusted
  - name: kubeconfig-build-k8s-prow-builds
    files:
      - kubeconfig=secrets/kubeconfig-build-k8s-prow-builds
  - name: kubeconfig-build-rules-k8s
    files:
      - kubeconfig=secrets/kubeconfig-build-rules-k8s
  - name: unsplash-api-key
    literals:
      - honk.txt=
  - name: kubevirtci-docker-credential
    namespace: kubevirt-prow-jobs
    # username=dockerUser
    # password=dockerPass
    envs:
    - secrets/kubevirtci-docker-credential
    type: Opaque

  - name: kubevirtci-quay-credential
    namespace: kubevirt-prow-jobs
    # username=quayUser
    # password=quayPass
    envs:
    - secrets/kubevirtci-quay-credential
    type: Opaque
  - name: kubevirtci-installer-pull-token
    namespace: kubevirt-prow-jobs
    files:
      # installerPullToken
      - token=secrets/kubevirtci-installer-pull-token
    type: Opaque
  - name: commenter-oauth-token
    namespace: kubevirt-prow-jobs
    # githubCommenterToken
    files:
      - oauth=secrets/commenter-oauth-token
    type: Opaque
  - name: kubevirtci-coveralls-token
    namespace: kubevirt-prow-jobs
    files:
      # coverallsToken
      - token=secrets/kubevirtci-coveralls-token
    type: Opaque
  - name: kubevirtci-fossa-token
    namespace: kubevirt-prow-jobs
    files:
      # fossaToken
      - token=secrets/kubevirtci-fossa-token
    type: Opaque
  - name: prow-kubevirtbot-github-ssh-secret
    namespace: kubevirt-prow-jobs
    files:
      # prowKubevirtbotSSHPrivateKey
      - token=secrets/prow-kubevirtbot-github-ssh-secret
    type: Opaque
